---
- hosts: all
  sudo: yes
  roles:
          - common

- hosts: etcd
  sudo: yes
  roles:
          - etcd
          - flannel-config

- hosts: masters
  sudo: yes
  roles:
          - kubernetes
          - master
          - skydns

- hosts: minions
  sudo: yes
  roles:
          - kubernetes
          - flannel
          - minion

