---
- name: Install kubernetes from RHEL7 packages
  yum: pkg=kubernetes state=latest

- name: write the global config file
  template: src=config.j2 dest=/etc/kubernetes/config
  notify:
          - restart daemons
